name: Keep Codespace Alive
on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        run: |
          curl -I "https://<your-codespace-url>"
