name: Keep Codespace Alive
on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        run: |
          curl -I "https://k8ngsparklr-tesop-s6yj661zp2p.ws-us116.gitpod.io/"
